# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-26 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('book_name', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('count', models.IntegerField(default=0, editable=False)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'In active')], default=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'verbose_name': 'books',
            },
        ),
    ]
