# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210626_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
